### ISSUE TITLE
Links separados para download de KML para aldeias habitadas e não habitadas (esbulhadas)

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/mapaguarani#118]
Ter links diferentes para baixar kml apenas de aldeias atuais, e apenas aldeias antigas. Esta informação é obtida pelo campo Presença Indígena (antigo Presença Guarani)

**Comment by tiagofassoni** [comment]
Feito no commit: https://github.com/hacklabr/mapaguarani/commit/8166689a151a687b6bb6a2f431f36a7e7dcda22a
