### ISSUE TITLE
Na Situação Fundiária (land tenure), alterar a ordem dos campos no admin

### ISSUE THREAD

**Issue by tiagofassoni** [hacklabr/mapaguarani#120]
Deve ficar como 1) Sem providências 2) Em estudo 3) Delimitada 4) Declarada 5) Homologada 6) Regularizada 7) Em Processo de desapropriação ou aquisição 8) Adquirida 9)Desapropriada)

**Comment by brunosmartin** [comment]
Da onde veio essa? Daquele doc antigo, não? acho q isso tá resolvido já.
