### ISSUE TITLE
Visão da single de aldeias, terras e sítios arqueológicos estão sem fundo

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/mapaguarani#23]
Basta clicar em um dos elementos pra ver.

**Comment by miguelpeixe** [comment]
era cache do seu browser?

**Comment by brunosmartin** [comment]
Pior... os css não estavam sendo gerados na produção. Resolvido já!

2015-11-08 13:41 GMT-02:00 Miguel Peixe <notifications@github.com>:

> era cache do seu browser?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hacklabr/mapaguarani/issues/23#issuecomment-154834319>
> .
>



-- 
Bruno Martin
Hacklab/
11 2892 0122
11 3862 1186
