### ISSUE TITLE
fazer zoom para terras indígenas ao selecionar

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/mapaguarani#25]

**Comment by miguelpeixe** [comment]
o resultado da api deve ser um bbox, coordenadas de ponto não permitem identificar a extensão da terra indígena tornando impossível determinar o zoom apropriado para a terra

**Comment by brunosmartin** [comment]
Estes pontos são os 4 cantos do bbox. Qual o formato q deve ter? Deve ser
um polígono?

Minha referência foi esta aqui:
http://geojson.org/geojson-spec.html#bounding-boxes


Em 8 de novembro de 2015 13:40, Miguel Peixe <notifications@github.com>
escreveu:

> o resultado da api deve ser um bbox, coordenadas de ponto não permitem
> identificar a extensão da terra indígena tornando impossível determinar o
> zoom apropriado para a terra
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hacklabr/mapaguarani/issues/25#issuecomment-154834267>
> .
>



-- 
Bruno Martin
Hacklab/
11 2892 0122
11 3862 1186

**Comment by miguelpeixe** [comment]
para entender melhor o bounding box como conceito vale ler a [documentação do leaflet a respeito](http://leafletjs.com/reference.html#latlngbounds)

sobre o formato na api, fica a seu critério, pode ser uma propriedade bbox dentro - ou não - de geometry, contendo um array de coordenadas

**Comment by brunosmartin** [comment]
Feito. Agora o formato ficou:
"bbox": [
        [
            -51.073412057039064,
            -30.407977420130806
        ],
        [
            -51.035308362615694,
            -30.369873725707436
        ]
    ],
