### ISSUE TITLE
Retirar as legendas de Aldeias e Sítios

### ISSUE THREAD

**Issue by luisfbs** [hacklabr/mapaguarani#28]
As tarefas dessa issue são:
- [ ] Retirada das legendas do lado direito;
- [x] Acrescentar as bolas referentes às cores antes dos seguintes títulos de menu: Aldeias Indígenas + Sítios Arqueológicos;

**Comment by ariadnemelo** [comment]
@luisfbs as legendas passam para outro lugar?
