### ISSUE TITLE
Ajustes na barra de ferramentas do menu lateral esquerdo

### ISSUE THREAD

**Issue by luisfbs** [hacklabr/mapaguarani#29]
Listas de tarefas:
- [ ] Ferramentas só aparecerem no hover (pode deixar por último);
- [x] Trocar o ícone de hamburguer pelo de lista no fontawesome;
- [x] Colocar label (legenda) em cima dos ícones (pode colocar fonte 12 que ai eu posso brincar amanhã com os tamanhos e a gente decidir o padrão da fonte e da tipografia);
- [ ] Na visualização máxima deixar o menu com 20% do tamanho, para economizar espaço, acho que o tamanho ficou conveniente, e aí a gente trabalha junto para desenhar melhor esse menu pro mobile;

**Comment by ariadnemelo** [comment]
@luisfbs to colocando uma label provisória pros ícones, depois você pode me dizer a label correta de cada um deles?
