### ISSUE TITLE
Modal abre por baixo dos boxes (menu lateral esquerdo, etc)

### ISSUE THREAD

**Issue by luisfbs** [hacklabr/mapaguarani#30]
Modal abre por baixo dos boxes (menu lateral esquerdo, etc)

**Comment by ariadnemelo** [comment]
Self-note: problema do z-index que o Bruno comentou

**Comment by ariadnemelo** [comment]
Feito em https://github.com/hacklabr/mapaguarani/commit/40b5446a55fff66365407ce85c8071c6b507baa6
