### ISSUE TITLE
Criar botão de minimalização no menu esquerdo

### ISSUE THREAD

**Issue by luisfbs** [hacklabr/mapaguarani#32]
- [x] Uma seta para a esquerda dentro uma abinha semicircular, como pensei no desenho (menu aberto)
- [x] Uma bolinha com a seta para direita e a palavra Menu em cima (menu fechado)

**Comment by ariadnemelo** [comment]
@luisfbs só para mim ter certeza de que entendi corretamente: a primeira opção é para quando o menu está aberto e a segunda para quando ele está fechado?

**Comment by brunosmartin** [comment]
Falta só fazer um animate pra ficar suave

**Comment by brunosmartin** [comment]
Falta os controles de zoom e camada acompanharem o hide
