### ISSUE TITLE
Implementar relatório de Situação Jurídica das Terras Indígenas

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/mapaguarani#34]

**Comment by fabiomontefuscolo** [comment]
Exportar relatório de terras indígenas com os seguinte campos:
Número, Terra Indígena TI  -  (Aldeias Guarani), Outras denominações da TI, Grupo(s) étnico(s), Subgrupo proeminente, Presença Guarani, Área da TI (ha),    Situação Jurídica, Documentação, Município, UF
