### ISSUE TITLE
Terça-feira: Tipografia e Detalhes

### ISSUE THREAD

**Issue by luisfbs** [hacklabr/mapaguarani#48]
# Menu de seleção e ferramentas
Estou enviando no fim uma imagem de exemplo que fiz no firefox usando o developer tools
![exemplo](https://cloud.githubusercontent.com/assets/5922977/11198198/14deb8f4-8caa-11e5-8913-14224ed08f72.png)

### Família de fonte para tudo
- [x] Roboto: <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'> (vamos testar essa aqui, acho que ficou bom no exemplo que mandei usando no nome da Terra Indígena)

### Search Box:
- [x] Search Box: altura 48px;

### Abas de Opções do Menu: Aldeias, Sítios e Terras
- [x] Fontes de título: 16px;

### Ferramentas das abas
- [x] Labels novas: Lista / Baixar / Visível (desta forma o visível dá melhor a ideia de que ele é uma função associada à visualização ou não daquela camada, o aprendizado fica mais fácil)
- [x] Fonte tamanho 12px
- [x] Deixar o olho com a cor verde com o seguinte código hexa: #aef458;

### Títulos das aldeias, terras e sítios dentro da lista
- [x] Fonte tamanho 16px

**Comment by luisfbs** [comment]
<link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>

**Comment by brunosmartin** [comment]
@ariadnemelo faltou a página do detalhe da aldeia, terras e sítios. Clica em uma delas da lista pra chegar nela.

@luisfbs precisa verificar se a fonte Roboto é livre e compatível com a licença AGPLv3
